=== cad106uk/market-access-frontend/src/data/schema/backend/barriers/barrier.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Detail of a report",

	"type": "object",
	"required": [
		"id",
		"barrier_type",
		"report",
		"current_status",
		"reported_on"
	],
	"properties": {

		"id": { "$ref": "$refs/common.json#/uuid" },

		"barrier_type": {
			"type": "object",
			"required": [
				"id",
				"title"
			],
			"properties": {

				"id": { "$ref": "$refs/common.json#/small-int" },
				"title": { "$ref": "$refs/common.json#/words" }
			}
		},

		"report": {
			"type": "object",
			"required": [
				"id",
				"problem_status",
				"company"
			],
			"properties": {

				"id": { "$ref": "$refs/common.json#/small-int" },

				"problem_status": {
					"type": "number",
					"enum": [ 1, 2, 3 ]
				},

				"company": {
					"type": "object",
					"required": [
						"id",
						"name",
						"sector_id",
						"sector_name"
					],
					"properties": {

						"id": { "$ref": "$refs/common.json#/uuid" },
						"name": { "$ref": "$refs/common.json#/words" },
						"sector_id": { "$ref": "$refs/common.json#/uuid" },
						"sector_name": { "$ref": "$refs/common.json#/words" }
					}
				}
			}
		},

		"current_status": {
			"type": "object",
			"required": [ "status" ],
			"properties": {
				"status": {
					"type": "number",
					"enum": [ 1, 2, 3, 4 ]
				}
			}
		},

		"reported_on": { "$ref": "$refs/common.json#/past-date" }
	}
}

=== cad106uk/market-access-frontend/src/test/app/fake-data/backend/barriers/barrier.json
{
   "id": "1be2d5b6-7b6b-4944-9366-03ef143ab930",
   "barrier_type": {
      "id": 15,
      "title": "sunt sapiente officiis"
   },
   "report": {
      "id": 7,
      "problem_status": 1,
      "company": {
         "id": "fc3dbdc3-b0ef-4f5c-b0ac-b42852cfb323",
         "name": "facere sint a",
         "sector_id": "5f9cd335-e3ea-48ab-b8cd-6a3970edeed1",
         "sector_name": "cumque ipsa quo"
      }
   },
   "current_status": {
      "status": 1
   },
   "reported_on": "Fri Apr 27 2018 05:20:40 GMT+0100 (BST)"
}
